import type { Metadata } from "next";
import "../app/lib/firebase";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { ReduxProvider } from "@/components/ReduxProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main className="flex-grow min-h-screen">
          <ReduxProvider>{children}</ReduxProvider>
        </main>

        <Footer />
      </body>
    </html>
  );
}
